import { Profile, Match, Message } from "@/types";

export const mockProfiles: Profile[] = [
  {
    id: "1",
    user_id: "u1",
    name: "Amira Hassan",
    age: 26,
    bio: "Art director by day, home chef by night. I believe the best conversations happen over good food and honest wine. Looking for someone who can keep up with my energy and slow down with me on Sunday mornings.",
    photos: [
      "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&auto=format&fit=crop&q=80",
    ],
    location: "Cairo, EG",
    distance: 2.4,
    interests: ["Art", "Cooking", "Hiking", "Photography"],
    occupation: "Art Director",
    education: "AUC – Fine Arts",
    height: 168,
    verified: true,
    online_status: "online",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    user_id: "u2",
    name: "Layla Al-Rashid",
    age: 29,
    bio: "Software engineer who escapes to the mountains when code gets heavy. Fluent in Python, sarcasm, and three human languages. Let's get lost somewhere interesting.",
    photos: [
      "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1488716820095-cbe80883c496?w=800&auto=format&fit=crop&q=80",
    ],
    location: "Dubai, UAE",
    distance: 5.1,
    interests: ["Tech", "Climbing", "Travel", "Coffee"],
    occupation: "Senior Engineer @ Noon",
    education: "AUS – Computer Science",
    height: 172,
    verified: true,
    online_status: "recently",
    last_seen: new Date(Date.now() - 1800000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    user_id: "u3",
    name: "Nour Khalil",
    age: 24,
    bio: "Marine biologist obsessed with ocean conservation. I spend more time underwater than most people know what to do with. Also: terrible at bowling, great at trivia nights.",
    photos: [
      "https://images.unsplash.com/photo-1502685104226-ee32379fefbe?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&auto=format&fit=crop&q=80",
    ],
    location: "Beirut, LB",
    distance: 8.3,
    interests: ["Diving", "Science", "Books", "Yoga"],
    occupation: "Marine Biologist",
    education: "AUB – Marine Science",
    height: 165,
    verified: false,
    online_status: "offline",
    last_seen: new Date(Date.now() - 86400000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    user_id: "u4",
    name: "Sara Mansour",
    age: 27,
    bio: "Architect building dreams — literally. I sketch cities in notebooks and redesign spaces in my head wherever I go. Firm believer in long walks, late breakfasts, and meaningful silences.",
    photos: [
      "https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?w=800&auto=format&fit=crop&q=80",
    ],
    location: "Amman, JO",
    distance: 12.7,
    interests: ["Architecture", "Design", "Music", "Travel"],
    occupation: "Architect",
    education: "JUST – Architecture",
    height: 170,
    verified: true,
    online_status: "online",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockMatches: Match[] = [
  {
    id: "m1",
    user1_id: "current",
    user2_id: "u1",
    matched_at: new Date(Date.now() - 3600000).toISOString(),
    unread_count: 2,
    profile: mockProfiles[0],
    last_message: {
      id: "msg1",
      match_id: "m1",
      sender_id: "u1",
      content: "I just made that recipe you mentioned 🍝",
      type: "text",
      read: false,
      created_at: new Date(Date.now() - 1800000).toISOString(),
    },
  },
  {
    id: "m2",
    user1_id: "current",
    user2_id: "u2",
    matched_at: new Date(Date.now() - 86400000).toISOString(),
    unread_count: 0,
    profile: mockProfiles[1],
    last_message: {
      id: "msg2",
      match_id: "m2",
      sender_id: "current",
      content: "That trail sounds incredible!",
      type: "text",
      read: true,
      created_at: new Date(Date.now() - 7200000).toISOString(),
    },
  },
  {
    id: "m3",
    user1_id: "current",
    user2_id: "u3",
    matched_at: new Date(Date.now() - 172800000).toISOString(),
    unread_count: 1,
    profile: mockProfiles[2],
    last_message: {
      id: "msg3",
      match_id: "m3",
      sender_id: "u3",
      content: "Are you free this weekend?",
      type: "text",
      read: false,
      created_at: new Date(Date.now() - 43200000).toISOString(),
    },
  },
];

export const mockMessages: Message[] = [
  {
    id: "1",
    match_id: "m1",
    sender_id: "u1",
    content: "Hey! Your profile really caught my attention 😊",
    type: "text",
    read: true,
    created_at: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: "2",
    match_id: "m1",
    sender_id: "current",
    content: "Thank you! I loved your photography work btw",
    type: "text",
    read: true,
    created_at: new Date(Date.now() - 7000000).toISOString(),
  },
  {
    id: "3",
    match_id: "m1",
    sender_id: "u1",
    content: "That means a lot! I saw you're into cooking too",
    type: "text",
    read: true,
    created_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "4",
    match_id: "m1",
    sender_id: "u1",
    content: "I just made that recipe you mentioned 🍝",
    type: "text",
    read: false,
    created_at: new Date(Date.now() - 1800000).toISOString(),
  },
];
